name: PR Validation

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Validate
        uses: projectbluefin/actions/bootc-build/validate-pr@b2481faee5bad2f2a25b64d6269b06399a2f44c0 # v1
        with:
          shellcheck-glob: "build/*.sh"
          dockerfile: "Containerfile"
          hadolint-config: ".hadolint.yaml"
