name: Validate Justfiles
permissions:
  contents: read

on:
  pull_request:
    paths:
      - "custom/ujust/**"
      - "Justfile"
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Install just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4

      - name: Validate Justfiles
        shell: bash
        run: |
          echo "Validating justfiles in custom/ujust/ directory..."

          set -xeuo pipefail

          # Validate root Justfile
          echo "::group:: Validating Justfile"
          just --unstable --fmt --check -f Justfile
          echo "::endgroup::"

          # Validate custom ujust files
          find "custom/ujust" -iname '*.just' -print0 | \
            while IFS= read -r -d '' justfile ; do \
              echo "::group:: ===$(basename "$justfile")==="
              just --unstable --fmt --check -f "$justfile"
              echo "::endgroup::"
            done

          echo "All justfiles are valid"
